language: node_js
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
after_success:
  - if [[ `npm -v` > 5* ]]; then npx codecov; fi
branches:
  only:
    - master
    - /^greenkeeper/.*$/
