language: node_js
notifications:
  email: false
node_js:
  - 'node'
  - '6'
  - '4'
before_script:
  - npm prune
after_success:
  - npm install -g codecov semantic-release
  - codecov
  - semantic-release pre && npm publish && semantic-release post
branches:
  only: master
